package com.gpetuhov.android.sampledagger;

import android.app.Application;

import com.gpetuhov.android.sampledagger.dagger.components.AppComponent;
import com.gpetuhov.android.sampledagger.dagger.components.DaggerAppComponent;
import com.gpetuhov.android.sampledagger.dagger.modules.AppModule;

public class SampleDaggerApp extends Application {

    private static AppComponent appComponent;

    @Override
    public void onCreate() {
        super.onCreate();

        // Build and keep AppComponent instance.
        // DaggerAppComponent is generated by Dagger.
        appComponent = DaggerAppComponent.builder()
                .appModule(new AppModule(this))
                .build();
    }

    public static AppComponent getAppComponent() {
        return appComponent;
    }
}
